name: Common Test

on: [pull_request, push]

env:
  LATEST_OTP_RELEASE: 27

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [25, 26, 27]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar3 ct
    - shell: bash
      name: Dialyzer
      run: |
        ./rebar3 clean -a
        ./rebar3 as dialyzer dialyzer
      if: ${{ matrix.otp_version == env.LATEST_OTP_RELEASE }}

  macos:
    name: Test on MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Brew Version Check
      run: brew --version
    - name: Brew Cleanup
      run: |
        brew cleanup --prune=all -s
        brew autoremove
    - name: Brew Untap Casks
      run: brew untap homebrew/cask homebrew/core
    - name: Keep Brew Fresh
      run: |
        brew update || true
        brew upgrade || true
    - name: Debug Brew
      run: brew doctor || true
    - name: Install Erlang
      #run: brew install erlang@${{ env.LATEST_OTP_RELEASE }}
      # fall back to OTP-26 since OTP 27.0 doesn't build on homebrew due to manpages issues
      run: brew install erlang@26
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar3 ct

  windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Erlang
      run: choco install erlang
    - name: Compile
      run: .\bootstrap.ps1
    - name: CT tests
      run: .\rebar3.ps1 ct
