name: Nightly

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Publish escript for every merge to master
    runs-on: ubuntu-latest

    container:
      image: erlang:19

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar3 ct

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy rebar3 escript to S3
      run: |
        aws s3 sync ./rebar3 s3://rebar3-nightly
