name: Publish

on:
  release:
    types: [published, created, edited]

jobs:
  build:
    name: Publish escript to release
    runs-on: ubuntu-latest

    container:
      image: erlang:19

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar3 ct

    # - name: Upload Release Asset
    #   id: upload-release-asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ github.event.release.upload_url }}
    #     asset_path: ./rebar3
    #     asset_name: rebar3
    #     asset_content_type: application/zip

    - name: Configure AWS credentials
      if: "!github.event.release.prerelease"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy rebar3 escript to S3
      if: "!github.event.release.prerelease"
      run: |
        aws s3 cp ./rebar3 s3://rebar3
